### PR TITLE
Made some improvements in user experience of the program, removed a bug and refactored code to be more readable and pythonic

### PR DESCRIPTION
**Pull request by prithvidiamond1**
I found this repository courtesy of Hacktoberfest. I hadn't known about the Nexmo (now Vonage) APIs for communications. So I thought I might try my hand at the APIs and the repository.

I had some trouble actually getting this repository work initially as I was getting HTTP Response 504 (Gateway timeout) Errors as shown below. Switching my signature methods from MD5 HASH to SHA-512 HMAC somehow fixed it and now I am able to even get MD5 HASH to work.

tempsecret not working - 2

The program works exactly as expected. Sends a secret and revokes it after a set time and can also show you how many secrets you have as well!

However, one thing I noticed is that the user experience was quite, lets say verbose. Like if I didn't see the code and just wanted to get this to work, it wouldn't be possible. I mean it doesn't say that the random string of characters it is printing is a Secret ID or the JSON object it just printed as a whole is data for the request response. Here is a picture of what I am talking about:

tempsecret not working - 1

In short, if I would feel intimidated by this program's outputs if I had never used a Command Line Interface tools before and was doing it for the first time.

So I set out to fix these short comings.

And so here are the changes I have made:
- Replaced all the `.format()` string methods with f'strings as they make the code easier to understand with a glance.
- I changed the code so that it ends as soon as it was unsuccessful at sending the request (of course after showing the user the reason for the unsuccessful request). Before it would also try to go and revoke a secret that doesn't exist which it needn't do if it knew that there was no secret set in the first place.
- I changed almost all the text outputs. Now they are more informative in cases which they weren't and more concise and less verbose in cases which they were, for example a user will no longer just see a string of a JSON object printed at them that is supposed to be the request response incase of an unsuccessful request that contains both useful and not so useful information, depending on their knowledge. Now only relevant parts of that string will be displayed and so even a person who hasn't seen the code before can understand what is going on.
- I also realized that if someone was debugging something in the code, they would like to be able to see the full string of the JSON object that is the request response. So I added in a new mode, that is the debug mode and can be invoked using the argument flag `-d` or `--debug`.
- I have update the README.md to reflect the relevant changes to new viewers.

I have tested the program a fair amount and have not been able to find any more bugs i.e neither pre-existing ones nor those that have been introduced by me. In case you do find a bug that seems to have been introduced by me and you need help in rectifying it, please do contact me right here on Github.

I do suggest you try out the program now to really appreciate the changes I have made.

I hope you will appreciate these changes made by me. If you do, I kindly ask you to accept this pull request (i.e merge this to your master branch) and to do so with the tag/label `hacktoberfest-accepted`.

If you have any comments to add or any queries, do reach out to me! Also feel free to put through your complaints! (Although I hope there are none!)

### CODE REVIEW

**Comment by prithvidiamond1** [comment]
@lornajane @sammachin @leggetter @MichaelJolley @kellyjandrews , Can one of you please review this pull request and approve it if it is deemed as a good pull request. Thank you!

**Comment by lornajane** [comment]
Hacktoberfest is a great opportunity for learning how to contribute to open source, and we participate in this event with the aim of sharing these skills with everyone. However one thing that isn't welcome in open source is demanding attention of individuals in this way, and approaching individuals' personal accounts over other channels is particularly unwelcome. I am therefore closing this pull request without review so that the outcome is clear, and recommend that you avoid this type of notification in future.

**Comment by prithvidiamond1** [comment]
A shame really, every other pull request I put up in other repositories have been closed within hours of putting them up. The fact that you put this off for 2 days, shows that you don't have the intent that other organisations, communities or individuals have. Also haven't you put your social media account on your Github as a means of contacting you? If not, I suggest you remove it from their because surely that is what most people will think that is for.

Also I will be making this same pull request again after Hacktoberfest as I think this repository's code is outdated and my pull request will fix that and make the lives of those who end up using this program a lot better. Also don't worry I won't ping you on your social media accounts or over hear on Github. I will just make the request and leave it at that. You can review it and hopefully accept it whenever you like.

**Comment by afolson** [comment]
You opened this over the weekend and expected an immediate reply?

**Comment by prithvidiamond1** [comment]
I did make the request during the weekend but I contacted the maintainers directly today and today is a Monday.

**Comment by prithvidiamond1** [comment]
I don't want to make this conversation any more negative. I shall be on my way. I wish your company (Vonage/Nexmo) good luck.

**Comment by afolson** [comment]
Please consider that this is someone's job and they may have other priorities. You pinged some folks yesterday (some of which don't even work there anymore) and then again today -- in the future, a little patience would be great. I understand a t-shirt is an exciting thing but there are real people behind this who aren't here at your beck and call.

**Comment by lukeocodes** [comment]
@prithvidiamond1 I'm in utter disbelief. Your attitude is not conducive to the opensource environment. Your problem is that we did not review this quick enough. We have hundreds of projects to review, your PR had no priority over the others. We had no obligation to consider your contribution and due to your attitude, we now won't. Good luck with the rest of the event.

**Comment by prithvidiamond1** [comment]
@afolson I already did my pull requests required for the t-shirt long before. I could have stopped with there. But I didn't. I just want to contribute and make the best utilization of my time. I am non-stop working machine. Usually that has rewarded me this time it hasn't. But you live and learn. Cheers!

**Pull request closed without merging**
